### ISSUE TITLE
Backpropagation of bn layer in caffe engine and cudnn engine

### ISSUE THREAD

**Issue by animebing** [yjxiong/caffe#163]
@yjxiong This issue is the subsequent one of #161. When I compute the diff for the bottom of bn layer, I find that the result in cudnn engine is much larger than that in caffe engine, which results in gradient explosion in former layer, and the same phenomenon occurs when I use SyncBN layer, so I hope you can check your code again to see whether there is something wrong, thanks

**Comment by yjxiong** [comment]
Can you post your network configs? I cannot reproduce the problem you mentioned.

Also, SyncBN only has one engine. Setting the `engine` option in SyncBN has no effect.

**Comment by animebing** [comment]
@yjxiong I make some change to your original version, So I fork your code to my github [https://github.com/animebing/caffe](url). You can `git clone`,  after that, there will be an extra testrun directory, in the directory, I write a readme.txt, you can find what changes I have made and how to reproduce the phenomenon in this file. In the link [https://drive.google.com/open?id=0B57WniZdIycYa0E0UURiR1pTUVE](url), there is the initial model I used, you can download it and put it in testrun/model.

The cmake and make command is the same as that in your github, because I use opencv 3.0, so I add `set (OpenCV_DIR /usr/local/opencv-3.0.0/share/OpenCV)` In cmake/Dependency.cmake. when I do  
`make build && cd build`
`cmake -DUSE_MPI=ON`
the generated cmake file is not in the build directory, so I use the command below
`cmkae -B. -H.. -DUSE_MPI=ON`

Above is all what I do with your code, thank you for helping me find what is wrong there

**Comment by yjxiong** [comment]
Your problem is simple.

https://github.com/animebing/caffe/blob/action_recog/testrun/prototxt/pspnet101_cityscapes_713_cudnn.prototxt#L58

`BN` does not support in-place operation. Maybe you didn't see NaNs in the Caffe implementation. But the results are still incorrect. The in-place manner you saw in the original PSPNet release prototxt is a misuse which is only possibly valid for testing. You should file an issue to the authors for this problem.
