### ISSUE TITLE
 demo.py run problem 

### ISSUE THREAD

**Issue by Jangol** [yjxiong/caffe#38]
@wanglimin 
when I run "demo.py"  I got :

   Traceback (most recent call last):
  File "demo.py", line 12, in <module>
    from VideoSpatialPrediction import VideoSpatialPrediction
  File "/home/yuanzhi/tools/caffe/action_python/VideoSpatialPrediction.py", line 11, in <module>
    import cv2
ImportError: No module named cv2

**Comment by yjxiong** [comment]
I guess you need OpenCV Python interface. If you use Anaconda, you can
install it via `conda install opencv`. Otherwise, you may have to manually
compile it.

On Fri, Jan 22, 2016 at 3:22 PM, Jangol notifications@github.com wrote:

> @wanglimin https://github.com/wanglimin
> when I run "demo.py" I got :
> 
> Traceback (most recent call last):
> File "demo.py", line 12, in
> from VideoSpatialPrediction import VideoSpatialPrediction
> File "/home/yuanzhi/tools/caffe/action_python/VideoSpatialPrediction.py",
> line 11, in
> import cv2
> ImportError: No module named cv2
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yjxiong/caffe/issues/38.

## 

熊元骏
Xiong, Yuanjun

Department of Information Engineering,
The Chinese University of Hong Kong.

E-mail: bitxiong@gmail.com
Mobile: +852 54282253
Mainland China Mobile: +86 147 1430 8814
Address: SHB703, The Chinese University of Hong Kong.
              Shatin, N.T, Hong Kong.

**Comment by Jangol** [comment]
@yjxiong 
Thank you ！
 `conda install opencv` worked.

**Comment by Jangol** [comment]
@yjxiong @wanglimin 

Does the action-Python  'demo.py' script：

 # input video (containing image__.jpg and flow__.jpg) and some settings
    input_video_dir = 'video/'
means the RGB ang FLow images should put in one 'video' folder?  I need to put all the 101 actions images in 'video' folder or just  one of the 101 actions?

Thanks !

**Comment by yjxiong** [comment]
One video

**Comment by Jangol** [comment]
@yjxiong 

Thank you very much !
